In [1]:
from typing import Dict, Tuple, Sequence
import glob
import pandas as pd
import numpy as np
import sys

sys.path.append("")

In [2]:
train_f = '../GPTime/data/raw/M4/M4train\\Yearly-train.csv'
test_f = '../GPTime/data/raw/M4/M4test\\Yearly-test.csv'

# Finding longest possible lag value for the dataset
num_non_na_train_int = 12
num_non_na_test_int = 6
print(f"num_non_na_train_int = {num_non_na_train_int}")
print(f"num_non_na_test_int = {num_non_na_test_int}")

# Creating the dataset
l_train_tmp = []
l_test_tmp = []
df_train = pd.read_csv(train_f, index_col=0)
df_test = pd.read_csv(test_f, index_col=0)
Y_train = df_train.to_numpy()
Y_test = df_test.to_numpy()
assert (Y_train.shape[0] == Y_test.shape[0]), f"Y_train.shape[0], {Y_train.shape[0]} differs from Y_test.shape[0], {Y_test.shape[0]}"
for i in range(Y_train.shape[0]):
    s_train = Y_train[i][~np.isnan(Y_train[i])]
    s_test = Y_test[i][~np.isnan(Y_test[i])]
    l_train_tmp.append(s_train[-num_non_na_train_int:])  # shortest in the train set
    l_test_tmp.append(s_test[:num_non_na_test_int])  # shortest in the test set

# Scaling using the scaling in MASE
df_train_out = pd.DataFrame(l_train_tmp)
df_test_out = pd.DataFrame(l_test_tmp)
# Find the seasonality of the ts
scale = (df_train.diff(periods=1, axis=1).abs().mean(axis=1).reset_index(drop=True))

X_train = df_train_out.div(scale, axis=0).values
X_test = df_test_out.div(scale, axis=0).values

print(f"X_train.shape = {X_train.shape}")
print(f"X_test.shape = {X_test.shape}")

np.save("M4_Yearly_train.npy", X_train)
np.save("M4_YEARLY_test.npy", X_test)  

num_non_na_train_int = 12
num_non_na_test_int = 6
X_train.shape = (23000, 12)
X_test.shape = (23000, 6)


In [46]:
df_train = pd.read_csv("../GPTime/data/raw/M4/M4train/Yearly-train.csv", index_col=0)
df_test = pd.read_csv("../GPTime/data/raw/M4/M4test/Yearly-test.csv", index_col=0)
scale = df_train.diff(periods=1, axis=1).abs().mean(axis=1).reset_index(drop=True)

In [47]:
print(df_train.shape, df_test.shape, scale.shape)

(23000, 835) (23000, 6) (23000,)


In [56]:
df_train_scaled = df_train.div(scale.values, axis=0)
df_test_scaled = df_test.div(scale.values, axis=0)

In [57]:
df_train_scaled.shape, df_test_scaled.shape 

((23000, 835), (23000, 6))

In [58]:
df_train_scaled

V2         V3         V4         V5         V6         V7  \
V1                                                                         
Y1      44.870735  44.535859  44.999132  44.111625  44.956622  46.971949   
Y2      10.981432  11.161804  12.700265   8.758621   7.915119   7.151194   
Y3      14.733096  15.907473  17.081851  18.416370  19.590747  20.551601   
Y4      15.918367  17.284144  18.649922  19.733124  20.910518  22.135008   
Y5      11.379310  11.666667  12.758621  14.540230  15.000000  15.632184   
...           ...        ...        ...        ...        ...        ...   
Y22996   2.239326   2.382261   2.725307   2.725307   2.901594   3.163643   
Y22997   1.519206   1.375762   1.561588   2.868887   3.455705   8.384975   
Y22998   3.995360   2.682715   2.740139   2.871810   2.610789   2.238399   
Y22999   0.265752   0.685170   0.667092   0.269368   0.213325   0.350720   
Y23000  43.866995  43.931034  44.955665  45.788177  46.364532  47.325123   

               V8         V9        V10        V11  ...  V827  V828  V829  \
V1                                                  ...                     
Y1      48.376518  49.909485  51.664546  52.814922  ...   NaN   NaN   NaN   
Y2       6.355438   6.323607   5.862069   5.347480  ...   NaN   NaN   NaN   
Y3      21.352313  22.206406  22.900356  24.181495  ...   NaN   NaN   NaN   
Y4      23.029827  23.830455  24.489796  25.855573  ...   NaN   NaN   NaN   
Y5      17.068966  17.126437  17.816092  18.563218  ...   NaN   NaN   NaN   
...           ...        ...        ...        ...  ...   ...   ...   ...   
Y22996   3.787795   4.006964   4.416712   4.531061  ...   NaN   NaN   NaN   
Y22997   9.734656   7.811198   4.961871   4.091425  ...   NaN   NaN   NaN   
Y22998   2.708817   3.676334   4.054524   4.257541  ...   NaN   NaN   NaN   
Y22999   0.471846   0.743021   1.164247   0.784601  ...   NaN   NaN   NaN   
Y23000  46.940887  48.157635  49.758621  50.783251  ...   NaN   NaN   NaN   

        V830  V831  V832  V833  V834  V835  V836  
V1                                                
Y1       NaN   NaN   NaN   NaN   NaN   NaN   NaN  
Y2       NaN   NaN   NaN   NaN   NaN   NaN   NaN  
Y3       NaN   NaN   NaN   NaN   NaN   NaN   NaN  
Y4       NaN   NaN   NaN   NaN   NaN   NaN   NaN  
Y5       NaN   NaN   NaN   NaN   NaN   NaN   NaN  
...      ...   ...   ...   ...   ...   ...   ...  
Y22996   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
Y22997   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
Y22998   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
Y22999   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
Y23000   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[23000 rows x 835 columns]

In [45]:
scale

0         115.266667
1         188.500000
2         187.333333
3         212.333333
4         174.000000
            ...     
22995     209.884615
22996    3067.391304
22997     172.400000
22998     553.147059
22999     156.153846
Length: 23000, dtype: float64

In [61]:
# Testing yearly data recursive
print(df_test.shape, df_train.shape)
print((df_train.div(scale, axis=0)).shape)
ts_train = df_train.div(scale.values, axis=0)
ts_test = df_test.div(scale.values, axis=0)
print(ts_train.shape, ts_test.shape)
#X_train_yearly = df_yearly_train.to_numpy()
#X_test_yearly = df_yearly_test.to_numpy()
X_train_yearly = ts_train.to_numpy()
X_test_yearly = ts_test.to_numpy()
ts_train = []
ts_test = []
for i in range(X_train_yearly.shape[0]):
    s_train = X_train_yearly[i][~np.isnan(X_train_yearly[i])]
    s_test = X_test_yearly[i][~np.isnan(X_test_yearly[i])]
    ts_train.append(s_train[-12:])  # shortest in the train set
    ts_test.append(s_test[:6])  # shortest in the test set

df_train_out = pd.DataFrame(ts_train)
df_test_out = pd.DataFrame(ts_test)

X_train_2 = np.array(ts_train)
X_test_2 = np.array(ts_test)

(23000, 6) (23000, 835)
(46000, 835)
(23000, 835) (23000, 6)


In [62]:
X_train - X_train_2

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
X_train, X_train_2

(array([[61.97802198, 62.72932331, 63.76171197, ..., 65.82388664,
         65.33111625, 62.99392713],
        [ 9.51724138,  7.56498674,  6.20689655, ...,  5.31564987,
          6.9071618 ,  8.50397878],
        [33.09608541, 34.80427046, 35.71174377, ..., 42.17081851,
         43.87900356, 44.73309609],
        ...,
        [ 5.52262181,  7.10208817,  8.91473318, ..., 10.80800464,
          7.90951276,  5.49883991],
        [ 5.79231137,  3.44393045,  3.6970277 , ..., 16.70080289,
         12.64401553, 11.40022332],
        [44.95566502, 45.78817734, 46.36453202, ..., 54.1773399 ,
         55.5862069 , 56.09852217]]),
 array([[7144. , 7230.6, 7349.6, ..., 7587.3, 7530.5, 7261.1],
        [1794. , 1426. , 1170. , ..., 1002. , 1302. , 1603. ],
        [6200. , 6520. , 6690. , ..., 7900. , 8220. , 8380. ],
        ...,
        [ 952.1, 1224.4, 1536.9, ..., 1863.3, 1363.6,  948. ],
        [3204. , 1905. , 2045. , ..., 9238. , 6994. , 6306. ],
        [7020. , 7150. , 7240. , ..., 8460. ,

In [29]:
df_a = pd.DataFrame({"v1":[1,2,3], "v2":[2,3,4]})
df_b = pd.DataFrame({"v3":[4,5,5], "v5":[6,3,5]})
df_a, df_b

(   v1  v2
 0   1   2
 1   2   3
 2   3   4,
    v3  v5
 0   4   6
 1   5   3
 2   5   5)

In [34]:
scale = df_b.diff(periods=1, axis=1).abs().mean(axis=1).reset_index(drop=True).values
scale

array([2., 2., 0.])

In [36]:
df_a.div(scale, axis=0)

v1   v2
0  0.5  1.0
1  1.0  1.5
2  inf  inf